---
- name: install nginx and start
  hosts: localhost
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
        name: nginx
        state: present
  - name: start nginx
    service:
        name: nginx 
        state: started
        enabled: yes