---
- name: variables another method
  hosts: frontend
  tasks:
  - name: print information
    debug:
      msg: "HELLO TARAKRAM we are teaching {{COURSE}}, trainer is {{TRAINER}}, session through {{MODE}}, please practice daily {{duration}} thank you Tarakram"