[frontend]
100.24.66.250

[backend]

[local]
localhost

[local:vars]
COURSE="ANSIBLE"
DURATION="10HRS"
TRAINER="SVK"
MODE="Online"

[frontend:vars]
COURSE="ANSIBLE"
DURATION="10HRS"
TRAINER="SVK"
MODE="Online"