[frontend]
172.31.43.211

[backend]

[local]
localhost

[local:vars]
COURSE="ANSIBLE"
DURATION="10HRS"
TRAINER="SVK"
MODE="Online"
IMP="CARE"

[frontend:vars]
COURSE="ANSIBLE"
DURATION="10HRS"
TRAINER="SVK"
MODE="Online"
IMP="CAREFULL"