[frontend]
172.31.32.154

[backend]

[local]
localhost

[local:vars]
COURSE="ANSIBLE"
DURATION="10HRS"
TRAINER="SVK"
MODE="Online"

[frontend:vars]
COURSE="ANSIBLE"
DURATION="10HRS"
TRAINER="SVK"
MODE="Online"